### ISSUE TITLE
Update template to Discord.js v14

### ISSUE THREAD

**Issue by krebinkkj** [EbaaCode/Djs-v13-bot-template#1]

**Comment by EbaaCode** [comment]
Hey, I'm currently working on updating this template for Discord.js v14, But If you have any suggestions, feel free to open a pull request.

**Comment by MrTheMech** [comment]
Hello EbaaCode!
I actually made this template work in v14. I will try cleaning my project and send a Pull Request as soon as possible! 🙂

**Comment by MrTheMech** [comment]
Contributed! 💖
My first PR proud 🔥

**Comment by Raz-js** [comment]
> Contributed! 💖 My first PR proud 🔥

Amazing PR, looks like it took a lot of effort
but damn thats a lot of files

**Comment by MrTheMech** [comment]
This issue is fixed I guess this issue could be closed.
